# Standards: 0.1
---
- name: Clear cache directory
  when: "homebrew_clear_cache | bool"
  file:
    path: "{{ homebrew_cache.stdout | trim }}"
    state: absent
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

...
